[target.arm-unknown-linux-gnueabi]
image.name = "debian-cross-rs-arm-unknown-linux-gnueabi:latest"
image.toolchain = ["aarch64-unknown-linux-gnu"]
pre-build = ["dpkg --add-architecture armel && apt-get update && apt-get install --assume-yes libudev-dev:armel"]
